import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import httpServer from 'http-server';

const root=fileURLToPath(new URL('../',import.meta.url));
const renders=join(root,'renders/duo');
await mkdir(renders,{recursive:true});
await mkdir(join(root,'output/duo'),{recursive:true});
const changed=(a,b,tolerance=.01)=>a.some((n,i)=>Math.abs(n-b[i])>tolerance);
let browser,server;
try {
  let base=process.env.PREVIEW_URL;
  if(!base){
    server=httpServer.createServer({root:join(root,'web'),cache:-1,showDir:false});
    await new Promise((resolve,reject)=>{server.server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
    base=`http://127.0.0.1:${server.server.address().port}/`;
  }
  const chrome=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  browser=await chromium.launch({headless:true,...(existsSync(chrome)?{executablePath:chrome}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  page.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});
  const url=new URL('duo/',base).href;
  await page.goto(url);
  await page.waitForFunction(()=>window.duo?.ready,null,{timeout:60000});
  const state=()=>page.evaluate(()=>window.duo.state());
  await page.evaluate(()=>window.duo.seek(0));
  const closed=await state();
  const loadedRequests=requests.length;
  assert.equal(closed.hinges.length,2);
  assert.ok(closed.clips>=1&&closed.meshes>30&&closed.triangles>10000,'Real Blender geometry and animated nodes must load');
  const snapshot=async name=>{await page.waitForTimeout(180);await page.screenshot({path:join(renders,`${name}.png`),fullPage:true});};
  await snapshot('browser-closed');
  await page.getByRole('button',{name:'Unfold surprise',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold>.25&&window.duo.state().fold<.8);
  const mid=await state();
  assert.ok(closed.hinges.every((q,i)=>changed(q,mid.hinges[i],.1)),'Both actual hinge nodes must rotate during opening');
  await page.waitForFunction(()=>window.duo.state().fold===1);
  const opened=await state();
  assert.ok(opened.hinges.every(q=>Math.abs(q[3])>.999),'Both halves must lie flat at 180 degrees');
  assert.equal(await page.locator('#angle').textContent(),'180°');
  await snapshot('browser-open');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold===0);
  assert.ok((await state()).hinges.every((q,i)=>!changed(q,closed.hinges[i],1e-5)),'Closing after the animation endpoint must restore both hinge rotations');
  await page.getByRole('slider',{name:'Open angle'}).fill('90');
  const half=await state();
  assert.equal(half.fold,.5);assert.equal(half.playing,false);
  assert.ok(half.hinges.every(q=>Math.abs(Math.abs(q[3])-Math.cos(Math.PI/8))<.002),'90-degree opening must put each leaf at 45 degrees');
  await snapshot('browser-folding');
  const frozen=await page.locator('canvas').evaluate(c=>c.toDataURL());
  await page.waitForTimeout(250);
  assert.equal(await page.locator('canvas').evaluate(c=>c.toDataURL()),frozen,'Pause must freeze the render');
  await page.getByRole('button',{name:'Play demo',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold>.6);
  await page.getByRole('button',{name:'Pause demo',exact:true}).click();
  assert.equal((await state()).playing,false);
  await page.evaluate(()=>{window.duo.seek(1);window.duo.setView('front',true);});
  const before=(await state()).camera;
  const box=await page.locator('canvas').boundingBox();
  await page.mouse.move(box.x+box.width*.45,box.y+box.height*.5);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width*.61,box.y+box.height*.52,{steps:15});
  await page.mouse.up();
  await page.waitForTimeout(450);
  assert.ok(changed(before,(await state()).camera,.5),'Dragging must orbit the real model');
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().camera[2]<-12);
  await snapshot('browser-back');
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'Save image',exact:true}).click();
  const download=await downloadEvent;
  assert.equal(download.suggestedFilename(),'apple-duo.png');
  await download.saveAs(join(renders,'download.png'));
  assert.ok((await readFile(join(renders,'download.png'))).length>10000);
  await page.waitForFunction(()=>document.getElementById('toast').hidden);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{window.duo.seek(1);window.duo.setView('hero',true);});
  await snapshot('browser-mobile');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile must not overflow horizontally');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold===0);
  await page.getByRole('button',{name:'Open',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold===1);
  assert.equal(requests.length,loadedRequests,'All interaction assets must already be local and loaded');
  assert.ok(requests.every(r=>new URL(r).origin===new URL(url).origin));
  assert.deepEqual(errors,[]);
  const calm=await browser.newPage({reducedMotion:'reduce'});
  await calm.goto(url);await calm.waitForFunction(()=>window.duo?.ready);
  assert.equal(await calm.evaluate(()=>window.duo.state().playing),false);
  assert.equal(await calm.evaluate(()=>window.duo.state().fold),1);
  await calm.close();
  // Exercise a full autoplay cycle, including its exact open endpoint and return.
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  await page.waitForFunction(()=>window.duo.state().fold===1,null,{timeout:15000});
  await page.waitForFunction(()=>window.duo.state().elapsed>10.9&&window.duo.state().fold<.01,null,{timeout:15000});
  assert.ok((await state()).hinges.every((q,i)=>!changed(q,closed.hinges[i],.02)));
  const report={passed:true,checks:['Blender geometry','two real hinges','180 degree open','close after endpoint','manual 90 degree pose','pause','resume','camera drag','back view and cover display','PNG download','mobile controls','local assets only','reduced motion','full autoplay cycle','no browser errors'],geometry:closed};
  await writeFile(join(root,'output/duo/verification.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report));
} finally {
  await browser?.close();
  if(server){server.server.closeAllConnections();await new Promise(resolve=>server.server.close(resolve));}
}
